//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual edits will be overwritten by the ResX designer.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BombaProMaxWPF.Resources
{
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Strongly-typed resource accessor for localized strings.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public static class Strings
    {
        private static ResourceManager? _resourceManager;
        private static CultureInfo? _resourceCulture;

        public static ResourceManager ResourceManager
        {
            get
            {
                _resourceManager ??= new ResourceManager(
                    "BombaProMaxWPF.Resources.Strings",
                    typeof(Strings).Assembly);
                return _resourceManager;
            }
        }

        /// <summary>Overrides the current thread's CurrentUICulture for lookups from this strongly-typed accessor.</summary>
        public static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        public static string AppName       => ResourceManager.GetString(nameof(AppName), _resourceCulture) ?? string.Empty;
        public static string Welcome       => ResourceManager.GetString(nameof(Welcome), _resourceCulture) ?? string.Empty;
        public static string Tagline       => ResourceManager.GetString(nameof(Tagline), _resourceCulture) ?? string.Empty;
        public static string GetStarted    => ResourceManager.GetString(nameof(GetStarted), _resourceCulture) ?? string.Empty;
        public static string ThemeLabel    => ResourceManager.GetString(nameof(ThemeLabel), _resourceCulture) ?? string.Empty;
        public static string LanguageLabel => ResourceManager.GetString(nameof(LanguageLabel), _resourceCulture) ?? string.Empty;
        public static string Light         => ResourceManager.GetString(nameof(Light), _resourceCulture) ?? string.Empty;
        public static string Dark          => ResourceManager.GetString(nameof(Dark), _resourceCulture) ?? string.Empty;
        public static string SignInTitle        => ResourceManager.GetString(nameof(SignInTitle), _resourceCulture) ?? string.Empty;
        public static string EmailLabel         => ResourceManager.GetString(nameof(EmailLabel), _resourceCulture) ?? string.Empty;
        public static string PasswordLabel      => ResourceManager.GetString(nameof(PasswordLabel), _resourceCulture) ?? string.Empty;
        public static string SignInButton       => ResourceManager.GetString(nameof(SignInButton), _resourceCulture) ?? string.Empty;
        public static string ForgotPassword     => ResourceManager.GetString(nameof(ForgotPassword), _resourceCulture) ?? string.Empty;
        public static string Connecting         => ResourceManager.GetString(nameof(Connecting), _resourceCulture) ?? string.Empty;
        public static string InvalidCredentials => ResourceManager.GetString(nameof(InvalidCredentials), _resourceCulture) ?? string.Empty;
    }
}
