// <auto-generated />
using System;
using BombaProMaxApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BombaProMaxApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123132733_InitialCreationOfDb")]
    partial class InitialCreationOfDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BombaProMaxApi.Models.Achat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("CamionID")
                        .HasColumnType("integer");

                    b.Property<int?>("ChauffeurID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FournisseurID")
                        .HasColumnType("integer");

                    b.Property<bool?>("LivraisonDefectueuse")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("PrixAchatUnitaire")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CamionID");

                    b.HasIndex("ChauffeurID");

                    b.HasIndex("FournisseurID");

                    b.HasIndex("ProduitID");

                    b.ToTable("Achats");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.AchatAllocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("AchatID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAllocation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("QuantiteAllouee")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ReservoirID")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UtilisateurAllocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.HasIndex("AchatID");

                    b.HasIndex("ReservoirID");

                    b.ToTable("AchatAllocations");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.BilanCredit", b =>
                {
                    b.Property<int>("BilanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BilanID"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<decimal>("CreditFacture")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("CreditNonFacture")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime>("DerniereMiseAJour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodeDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PeriodeFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("TotalPaye")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("BilanID");

                    b.HasIndex("ClientID")
                        .IsUnique();

                    b.ToTable("BilansCredit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Camion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int?>("CiterneID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FournisseurID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Marque")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Matricule")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CiterneID");

                    b.HasIndex("FournisseurID");

                    b.ToTable("Camions");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Categorie", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Chauffeur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FournisseurID")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroPermis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.HasIndex("FournisseurID");

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Citerne", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Capacite")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FournisseurID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("MatriculeCiterne")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<long?>("PartitionsNumber")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("FournisseurID");

                    b.ToTable("Citernes");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("CIN");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Contact");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateCreation");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateModification");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Nom");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NomSociete");

                    b.Property<string>("NumeroClient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NumeroClient");

                    b.Property<int>("userID")
                        .HasColumnType("integer")
                        .HasColumnName("userID");

                    b.HasKey("ID");

                    b.HasIndex("CIN")
                        .IsUnique();

                    b.HasIndex("NumeroClient")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("BombaProMaxApi.Models.CreditTransaction", b =>
                {
                    b.Property<int>("CreditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCredit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Facture")
                        .HasColumnType("boolean");

                    b.Property<int?>("FactureID")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("NumeroTransaction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PrixTTC")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("integer");

                    b.HasKey("CreditID");

                    b.HasIndex("ClientID");

                    b.HasIndex("FactureID");

                    b.HasIndex("ProduitID");

                    b.HasIndex("ServiceID");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Depense", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.ToTable("Depenses");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.ElementsFacture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("FactureID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("FactureID");

                    b.HasIndex("ProduitID");

                    b.HasIndex("ServiceID");

                    b.ToTable("ÉlémentsFacture");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Employe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Salaire")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("ID");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Facture", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("DateFacture")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePaiement")
                        .HasColumnType("date");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("MoyenPaiementID")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("MoyenPaiementID");

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Fournisseur", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ConditionsPaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RIB")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Societe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.IndicateursFinancier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("BeneficeNet")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("ChiffreAffairesTotal")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DebutPeriode")
                        .HasColumnType("date");

                    b.Property<decimal?>("DepensesTotales")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateOnly?>("FinPeriode")
                        .HasColumnType("date");

                    b.Property<decimal?>("TotalAchats")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("TotalCarburantVendu")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("TotalProduitsVendus")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("TotalServicesVendus")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("TotalVentes")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ID");

                    b.ToTable("IndicateursFinanciers");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Jaugeage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateJaugeage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroJaugeage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TemoinID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TemoinID");

                    b.ToTable("Jaugeages");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.JaugeageDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal>("HauteurMesuree")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("JaugeageID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ReservoirID")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("VolumeCalcule")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ID");

                    b.HasIndex("JaugeageID");

                    b.HasIndex("ReservoirID");

                    b.ToTable("JaugeageDetails");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.JoursActivite", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("ChiffreAffaires")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("FraisExploitation")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("ID");

                    b.ToTable("JoursActivité");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.MoyensPaiement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.ToTable("MoyensPaiement");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Periode", b =>
                {
                    b.Property<int>("PeriodeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodeID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeID")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.HasKey("PeriodeID");

                    b.HasIndex("EmployeID");

                    b.ToTable("Periodes");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.PeriodeDetails", b =>
                {
                    b.Property<int>("PeriodeDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PeriodeDetailID"));

                    b.Property<decimal>("CompteurElectroniqueDebut")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CompteurElectroniqueFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CompteurMecaniqueDebut")
                        .HasColumnType("numeric");

                    b.Property<decimal>("CompteurMecaniqueFinal")
                        .HasColumnType("numeric");

                    b.Property<int>("PeriodeID")
                        .HasColumnType("integer");

                    b.Property<int?>("PompeID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixCarburant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProduitID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int?>("ReservoirID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("PeriodeDetailID");

                    b.HasIndex("PeriodeID");

                    b.HasIndex("PompeID");

                    b.HasIndex("ProduitID");

                    b.HasIndex("ReservoirID");

                    b.ToTable("PeriodeDetails");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Pompe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CompteurElectroniqueActuel")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<decimal?>("CompteurMecaniqueActuel")
                        .HasColumnType("decimal(18, 3)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ReservoirAssocieID")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("ReservoirAssocieID");

                    b.ToTable("Pompes");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Produit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int?>("CategorieID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DelaiDeLivraison")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroProduit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("PrixAchat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PrixHT")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PrixTTC")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<int?>("StockMinimum")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TVA")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ID");

                    b.HasIndex("CategorieID");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.ReglementCredit", b =>
                {
                    b.Property<int>("ReglementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReglementID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateReglement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ModePaiementID")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ReferenceTransaction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValidePar")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ReglementID");

                    b.HasIndex("ClientID");

                    b.HasIndex("ModePaiementID");

                    b.ToTable("ReglementsCredit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Reservoir", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<decimal>("Capacite")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal>("NiveauDeCarburant")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("ProduitID");

                    b.ToTable("Reservoirs");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Service", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("Prix")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<bool>("AddAchat")
                        .HasColumnType("boolean")
                        .HasColumnName("AddAchat");

                    b.Property<bool>("AddBonFacturation")
                        .HasColumnType("boolean")
                        .HasColumnName("AddBonFacturation");

                    b.Property<bool>("CanManageCategories")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageCategories");

                    b.Property<bool>("CanManageCustomers")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageCustomers");

                    b.Property<bool>("CanManageProducts")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageProducts");

                    b.Property<bool>("CanManagePromotions")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManagePromotions");

                    b.Property<bool>("CanManageSales")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageSales");

                    b.Property<bool>("CanManageSettings")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageSettings");

                    b.Property<bool>("CanManageSuppliers")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageSuppliers");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("boolean")
                        .HasColumnName("CanManageUsers");

                    b.Property<bool>("CanViewReports")
                        .HasColumnType("boolean")
                        .HasColumnName("CanViewReports");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("EditCiternes")
                        .HasColumnType("boolean")
                        .HasColumnName("EditCiternes");

                    b.Property<bool>("EditClients")
                        .HasColumnType("boolean")
                        .HasColumnName("EditClients");

                    b.Property<bool>("EditLivreur")
                        .HasColumnType("boolean")
                        .HasColumnName("EditLivreur");

                    b.Property<bool>("EditPistolets")
                        .HasColumnType("boolean")
                        .HasColumnName("EditPistolets");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("IsSuperAdmin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<bool>("ShowAcceuil")
                        .HasColumnType("boolean")
                        .HasColumnName("ShowAcceuil");

                    b.Property<bool>("ShowDepenses")
                        .HasColumnType("boolean")
                        .HasColumnName("ShowDepenses");

                    b.Property<bool>("ShowTableauDeBord")
                        .HasColumnType("boolean")
                        .HasColumnName("ShowTableauDeBord");

                    b.Property<bool>("ShowVente")
                        .HasColumnType("boolean")
                        .HasColumnName("ShowVente");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("createdBy")
                        .HasColumnType("integer")
                        .HasColumnName("createdBy");

                    b.Property<int>("updatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updatedBy");

                    b.HasKey("UserId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 5,
                            AddAchat = true,
                            AddBonFacturation = true,
                            CanManageCategories = true,
                            CanManageCustomers = true,
                            CanManageProducts = true,
                            CanManagePromotions = true,
                            CanManageSales = true,
                            CanManageSettings = true,
                            CanManageSuppliers = true,
                            CanManageUsers = true,
                            CanViewReports = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditCiternes = true,
                            EditClients = true,
                            EditLivreur = true,
                            EditPistolets = true,
                            Email = "admin@bombapromax.com",
                            IsActive = true,
                            IsAdmin = true,
                            IsSuperAdmin = false,
                            Name = "Admin User",
                            Password = "Admin@123",
                            ShowAcceuil = true,
                            ShowDepenses = true,
                            ShowTableauDeBord = true,
                            ShowVente = true,
                            UpdatedAt = new DateTime(2025, 11, 23, 13, 27, 32, 618, DateTimeKind.Utc).AddTicks(1063),
                            createdBy = 0,
                            updatedBy = 0
                        },
                        new
                        {
                            UserId = 6,
                            AddAchat = true,
                            AddBonFacturation = true,
                            CanManageCategories = true,
                            CanManageCustomers = true,
                            CanManageProducts = true,
                            CanManagePromotions = true,
                            CanManageSales = true,
                            CanManageSettings = true,
                            CanManageSuppliers = true,
                            CanManageUsers = true,
                            CanViewReports = true,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EditCiternes = true,
                            EditClients = true,
                            EditLivreur = true,
                            EditPistolets = true,
                            Email = "superadmin@bombapromax.com",
                            IsActive = true,
                            IsAdmin = true,
                            IsSuperAdmin = true,
                            Name = "Super Admin",
                            Password = "SuperAdmin@123",
                            ShowAcceuil = true,
                            ShowDepenses = true,
                            ShowTableauDeBord = true,
                            ShowVente = true,
                            UpdatedAt = new DateTime(2025, 11, 23, 13, 27, 32, 618, DateTimeKind.Utc).AddTicks(1075),
                            createdBy = 0,
                            updatedBy = 0
                        });
                });

            modelBuilder.Entity("BombaProMaxApi.Models.VenteLubrifiantsEtArticles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<string>("CreePar")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateVente")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeID")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiePar")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("MoyenPaiementID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroVente")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("PrixUnitaireTTC")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteVendue")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("EmployeID");

                    b.HasIndex("MoyenPaiementID");

                    b.HasIndex("ProduitID");

                    b.ToTable("VenteLubrifiantsEtArticles");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Achat", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Camion", "Camion")
                        .WithMany("Achats")
                        .HasForeignKey("CamionID");

                    b.HasOne("BombaProMaxApi.Models.Chauffeur", "Chauffeur")
                        .WithMany("Achats")
                        .HasForeignKey("ChauffeurID");

                    b.HasOne("BombaProMaxApi.Models.Fournisseur", "Fournisseur")
                        .WithMany("Achats")
                        .HasForeignKey("FournisseurID");

                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany("Achats")
                        .HasForeignKey("ProduitID");

                    b.Navigation("Camion");

                    b.Navigation("Chauffeur");

                    b.Navigation("Fournisseur");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.AchatAllocation", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Achat", "Achat")
                        .WithMany("AchatAllocations")
                        .HasForeignKey("AchatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Reservoir", "Reservoir")
                        .WithMany("AchatAllocations")
                        .HasForeignKey("ReservoirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achat");

                    b.Navigation("Reservoir");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.BilanCredit", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Client", "Client")
                        .WithOne("BilanCredit")
                        .HasForeignKey("BombaProMaxApi.Models.BilanCredit", "ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Camion", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Citerne", "Citerne")
                        .WithMany("Camion")
                        .HasForeignKey("CiterneID");

                    b.HasOne("BombaProMaxApi.Models.Fournisseur", "Fournisseur")
                        .WithMany("Camion")
                        .HasForeignKey("FournisseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citerne");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Chauffeur", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Fournisseur", "Fournisseur")
                        .WithMany("Chauffeurs")
                        .HasForeignKey("FournisseurID");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Citerne", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Fournisseur", "Fournisseur")
                        .WithMany("Citerne")
                        .HasForeignKey("FournisseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.CreditTransaction", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Client", "Client")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Facture", "FactureAssociee")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("FactureID");

                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("ProduitID");

                    b.HasOne("BombaProMaxApi.Models.Service", "Service")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("ServiceID");

                    b.Navigation("Client");

                    b.Navigation("FactureAssociee");

                    b.Navigation("Produit");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.ElementsFacture", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Facture", "Facture")
                        .WithMany("ElementsFactures")
                        .HasForeignKey("FactureID");

                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany("ElementsFactures")
                        .HasForeignKey("ProduitID");

                    b.HasOne("BombaProMaxApi.Models.Service", "Service")
                        .WithMany("ElementsFactures")
                        .HasForeignKey("ServiceID");

                    b.Navigation("Facture");

                    b.Navigation("Produit");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Facture", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Client", "Client")
                        .WithMany("Factures")
                        .HasForeignKey("ClientID");

                    b.HasOne("BombaProMaxApi.Models.MoyensPaiement", "MoyenPaiement")
                        .WithMany("Factures")
                        .HasForeignKey("MoyenPaiementID");

                    b.Navigation("Client");

                    b.Navigation("MoyenPaiement");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Jaugeage", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Employe", "Temoin")
                        .WithMany("Jaugeages")
                        .HasForeignKey("TemoinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temoin");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.JaugeageDetail", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Jaugeage", "Jaugeage")
                        .WithMany("JaugeageDetails")
                        .HasForeignKey("JaugeageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Reservoir", "Reservoir")
                        .WithMany("JaugeageDetails")
                        .HasForeignKey("ReservoirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jaugeage");

                    b.Navigation("Reservoir");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Periode", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeID");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.PeriodeDetails", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Periode", "Periode")
                        .WithMany("PeriodeDetails")
                        .HasForeignKey("PeriodeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Pompe", "Pompe")
                        .WithMany()
                        .HasForeignKey("PompeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.Reservoir", "Reservoir")
                        .WithMany()
                        .HasForeignKey("ReservoirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Periode");

                    b.Navigation("Pompe");

                    b.Navigation("Produit");

                    b.Navigation("Reservoir");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Pompe", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Reservoir", "ReservoirAssocie")
                        .WithMany("Pompes")
                        .HasForeignKey("ReservoirAssocieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReservoirAssocie");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Produit", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieID");

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.ReglementCredit", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Client", "Client")
                        .WithMany("ReglementsCredit")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BombaProMaxApi.Models.MoyensPaiement", "ModePaiement")
                        .WithMany("ReglementsCredit")
                        .HasForeignKey("ModePaiementID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ModePaiement");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Reservoir", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany("Reservoirs")
                        .HasForeignKey("ProduitID");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.VenteLubrifiantsEtArticles", b =>
                {
                    b.HasOne("BombaProMaxApi.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID");

                    b.HasOne("BombaProMaxApi.Models.Employe", "Employe")
                        .WithMany()
                        .HasForeignKey("EmployeID");

                    b.HasOne("BombaProMaxApi.Models.MoyensPaiement", "MoyenPaiement")
                        .WithMany()
                        .HasForeignKey("MoyenPaiementID");

                    b.HasOne("BombaProMaxApi.Models.Produit", "Produit")
                        .WithMany("VentesLubrifiantsEtArticles")
                        .HasForeignKey("ProduitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employe");

                    b.Navigation("MoyenPaiement");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Achat", b =>
                {
                    b.Navigation("AchatAllocations");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Camion", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Chauffeur", b =>
                {
                    b.Navigation("Achats");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Citerne", b =>
                {
                    b.Navigation("Camion");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Client", b =>
                {
                    b.Navigation("BilanCredit");

                    b.Navigation("CreditTransactions");

                    b.Navigation("Factures");

                    b.Navigation("ReglementsCredit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Employe", b =>
                {
                    b.Navigation("Jaugeages");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Facture", b =>
                {
                    b.Navigation("CreditTransactions");

                    b.Navigation("ElementsFactures");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Fournisseur", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Camion");

                    b.Navigation("Chauffeurs");

                    b.Navigation("Citerne");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Jaugeage", b =>
                {
                    b.Navigation("JaugeageDetails");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.MoyensPaiement", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("ReglementsCredit");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Periode", b =>
                {
                    b.Navigation("PeriodeDetails");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Produit", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("CreditTransactions");

                    b.Navigation("ElementsFactures");

                    b.Navigation("Reservoirs");

                    b.Navigation("VentesLubrifiantsEtArticles");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Reservoir", b =>
                {
                    b.Navigation("AchatAllocations");

                    b.Navigation("JaugeageDetails");

                    b.Navigation("Pompes");
                });

            modelBuilder.Entity("BombaProMaxApi.Models.Service", b =>
                {
                    b.Navigation("CreditTransactions");

                    b.Navigation("ElementsFactures");
                });
#pragma warning restore 612, 618
        }
    }
}
