namespace FourniProApi.DTOs;

/// <summary>Used for both GET responses and POST/PUT request bodies.</summary>
public class AvoirDto
{
    public int AvoirId { get; set; }

    /// <summary>Read-only on GET; auto-generated by the API on create.</summary>
    public string? NumeroAvoir { get; set; }

    public DateOnly DateAvoir { get; set; }

    // ── Source (exactly one non-null) ─────────────────────────────────────────

    public int? VenteId { get; set; }
    /// <summary>Resolved on GET.</summary>
    public string? NumeroVente { get; set; }

    public int? CreditId { get; set; }
    /// <summary>Resolved on GET.</summary>
    public string? NumeroCredit { get; set; }

    // ── FKs + resolved names ──────────────────────────────────────────────────

    /// <summary>Null when source is Credit.</summary>
    public int? ProduitId { get; set; }
    public string? ProduitNom { get; set; }

    public int? ClientId { get; set; }
    public string? ClientNom { get; set; }

    public int? EmployeId { get; set; }
    public string? EmployeNom { get; set; }

    // ── Financial ─────────────────────────────────────────────────────────────

    /// <summary>Null when source is Credit.</summary>
    public int? Quantite { get; set; }

    /// <summary>Null when source is Credit.</summary>
    public decimal? PrixUnitaire { get; set; }

    /// <summary>Computed server-side. Always set.</summary>
    public decimal? MontantAvoir { get; set; }

    // ── Classification ────────────────────────────────────────────────────────

    public string? Raison { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }
    public string? ReferenceFile { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public string? AjouteParNom { get; set; }
    public DateTime? DateCreation { get; set; }

    public int? ModifiePar { get; set; }
    public string? ModifieParNom { get; set; }
    public DateTime? DateModification { get; set; }
}
