namespace FourniProApi.DTOs;

/// <summary>Used for both GET responses and POST/PUT request bodies.</summary>
public class CreditFournisseurDto
{
    public int CreditFournisseurId { get; set; }

    /// <summary>Read-only on GET; auto-generated by the API on create.</summary>
    public string? NumeroCreditF { get; set; }

    public DateOnly DateCredit { get; set; }

    // ── FKs + resolved names ──────────────────────────────────────────────────

    public int? AchatId { get; set; }
    public string? AchatNumero { get; set; }

    public int? FournisseurId { get; set; }
    public string? FournisseurNom { get; set; }

    public int? EmployeId { get; set; }
    public string? EmployeNom { get; set; }

    // ── Financial ─────────────────────────────────────────────────────────────

    /// <summary>Computed server-side from Achat.Cout — ignored on write.</summary>
    public decimal? MontantTotal { get; set; }

    // ── Statut ────────────────────────────────────────────────────────────────

    public string? Statut { get; set; }

    // ── Chèque ────────────────────────────────────────────────────────────────

    /// <summary>Nullable — presence implies a cheque was left.</summary>
    public string? ChequeReference { get; set; }

    /// <summary>Nullable — null when no cheque.</summary>
    public string? StatutCheque { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public string? AjouteParNom { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public string? ModifieParNom { get; set; }
    public DateTime? DateModification { get; set; }
}
