namespace FourniProApi.DTOs;

/// <summary>Used for both GET responses and POST/PUT request bodies.</summary>
public class CreditDto
{
    public int CreditId { get; set; }

    /// <summary>Read-only on GET; auto-generated by the API on create.</summary>
    public string? NumeroCredit { get; set; }

    public DateOnly DateCredit { get; set; }

    // ── FKs + resolved names ──────────────────────────────────────────────────

    public int? ProduitID { get; set; }
    public string? ProduitNom { get; set; }

    public int? ClientID { get; set; }
    public string? ClientNom { get; set; }

    public int? VoyageID { get; set; }
    public string? VoyageNumero { get; set; }

    public int? EmployeId { get; set; }
    public string? EmployeNom { get; set; }

    // ── Financial ─────────────────────────────────────────────────────────────

    public int? Quantite { get; set; }
    public decimal? PrixUnitaire { get; set; }
    public decimal? Remise { get; set; }

    /// <summary>Computed server-side: PrixUnitaire * Quantite - Remise.</summary>
    public decimal? MontantTotal { get; set; }

    // ── Statut ────────────────────────────────────────────────────────────────

    public string? Statut { get; set; }

    // ── Chèque ────────────────────────────────────────────────────────────────

    /// <summary>Nullable — presence implies a cheque was left.</summary>
    public string? ChequeReference { get; set; }

    /// <summary>Nullable — null when no cheque.</summary>
    public string? StatutCheque { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }
    public string? Reference { get; set; }
    public string? ReferenceFile { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public string? AjouteParNom { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public string? ModifieParNom { get; set; }
    public DateTime? DateModification { get; set; }
}
