//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable

namespace FourniPro.Resources;

using System;
using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    internal Strings() { }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            resourceMan ??= new global::System.Resources.ResourceManager("FourniPro.Resources.Strings", typeof(Strings).Assembly);
            return resourceMan;
        }
    }

    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    internal static string? GetString(string key)
        => ResourceManager.GetString(key, resourceCulture);

    internal static string InvalidCredentials
        => ResourceManager.GetString(nameof(InvalidCredentials), resourceCulture) ?? nameof(InvalidCredentials);

    internal static string AppName
        => ResourceManager.GetString(nameof(AppName), resourceCulture) ?? nameof(AppName);
}
