using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FourniProApi.Models;

/// <summary>Reason categories for an avoir (credit note).</summary>
public enum AvoirRaison
{
    Retour,
    Defectueux,
    ErreurFacturation,
    TropPercu,    // Credit source only
    Annulation,   // Vente deletion
    Autre
}

public class Avoir
{
    [Key]
    public int AvoirId { get; set; }

    /// <summary>Auto-generated by the API: AVR-{DateAvoir:yyyyMMdd}-{id:D5}</summary>
    [StringLength(30)]
    public string? NumeroAvoir { get; set; }

    public DateOnly DateAvoir { get; set; }

    // ── Source: exactly one of VenteId / CreditId is non-null ────────────────

    public int? VenteId { get; set; }
    public virtual Vente? Vente { get; set; }

    public int? CreditId { get; set; }
    public virtual Credit? Credit { get; set; }

    // ── FKs (no nav properties needed — resolved via name queries) ────────────

    /// <summary>Populated only when source is Vente.</summary>
    public int? ProduitId { get; set; }

    public int? ClientId { get; set; }

    public int? EmployeId { get; set; }
    public virtual Employe? Employe { get; set; }

    // ── Financial (Vente-source fields are null when source is Credit) ─────────

    /// <summary>Null when source is Credit.</summary>
    public int? Quantite { get; set; }

    /// <summary>Snapshot at avoir creation time. Null when source is Credit.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? PrixUnitaire { get; set; }

    /// <summary>
    /// Always set. 
    /// From Vente  → Quantite × PrixUnitaire.
    /// From Credit → SUM(PaiementCredit.Montant) − Credit.MontantTotal.
    /// </summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? MontantAvoir { get; set; }

    // ── Classification ────────────────────────────────────────────────────────

    /// <summary>Stored as string to match existing PaymentMethod pattern.</summary>
    [StringLength(30)]
    public string? Raison { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }

    [StringLength(500)]
    public string? ReferenceFile { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public DateTime? DateModification { get; set; }
}
