using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FourniProApi.Models;

/// <summary>Statut global du crédit.</summary>
public enum CreditStatut
{
    Impayé,
    Partiel,
    Soldé
}

/// <summary>Statut du chèque laissé en garantie (nullable — null quand pas de chèque).</summary>
public enum StatutCheque
{
    Détenu,
    Retourné,
    Déposé
}

public class Credit
{
    [Key]
    public int CreditId { get; set; }

    /// <summary>Auto-generated by the API: CRD-{yyyyMMdd}-{id:D5}</summary>
    [StringLength(30)]
    public string? NumeroCredit { get; set; }

    public DateOnly DateCredit { get; set; }

    // ── FKs ──────────────────────────────────────────────────────────────────

    public int? ProduitID { get; set; }
    public int? ClientID { get; set; }

    public int? VoyageID { get; set; }

    public int? EmployeId { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    public virtual Voyage? Voyage { get; set; }
    public virtual Employe? Employe { get; set; }
    public virtual ICollection<PaiementCredit> PaiementsCredit { get; set; } = [];
    public virtual ICollection<Avoir> Avoirs { get; set; } = [];

    // ── Financial ─────────────────────────────────────────────────────────────

    public int? Quantite { get; set; }

    /// <summary>Snapshot of the unit price at credit creation time.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? PrixUnitaire { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal? Remise { get; set; }

    /// <summary>Computed and stored: PrixUnitaire * Quantite - Remise.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? MontantTotal { get; set; }

    // ── Statut ────────────────────────────────────────────────────────────────

    [StringLength(20)]
    public string? Statut { get; set; }

    // ── Chèque ────────────────────────────────────────────────────────────────

    /// <summary>Cheque reference number. Nullable — presence implies a cheque was left.</summary>
    [StringLength(100)]
    public string? ChequeReference { get; set; }

    /// <summary>Nullable cheque status — null when no cheque.</summary>
    [StringLength(20)]
    public string? StatutCheque { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }

    [StringLength(200)]
    public string? Reference { get; set; }

    [StringLength(500)]
    public string? ReferenceFile { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public DateTime? DateModification { get; set; }
}
