using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FourniProApi.Models;

/// <summary>Statut global du crédit fournisseur.</summary>
public enum CreditFournisseurStatut
{
    NonPayé,
    PartielPayé,
    Payé
}

public class CreditFournisseur
{
    [Key]
    public int CreditFournisseurId { get; set; }

    /// <summary>Auto-generated by the API: CF-{DateCredit:yyyyMMdd}-{id:D5}</summary>
    [StringLength(30)]
    public string? NumeroCreditF { get; set; }

    public DateOnly DateCredit { get; set; }

    // ── FKs ──────────────────────────────────────────────────────────────────

    public int? AchatId { get; set; }
    public int? FournisseurId { get; set; }
    public int? EmployeId { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    public virtual Achat? Achat { get; set; }
    public virtual Fournisseur? Fournisseur { get; set; }
    public virtual Employe? Employe { get; set; }
    public virtual ICollection<PaiementFournisseur> PaiementsFournisseur { get; set; } = [];

    // ── Financial ─────────────────────────────────────────────────────────────

    /// <summary>Computed server-side from Achat.Cout — not trusted from client.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? MontantTotal { get; set; }

    // ── Statut ────────────────────────────────────────────────────────────────

    /// <summary>Stored as string — values from <see cref="CreditFournisseurStatut"/>.</summary>
    [StringLength(20)]
    public string? Statut { get; set; }

    // ── Chèque ────────────────────────────────────────────────────────────────

    /// <summary>Nullable — presence implies a cheque was left.</summary>
    [StringLength(100)]
    public string? ChequeReference { get; set; }

    /// <summary>Nullable — null when no cheque. Values from <see cref="StatutCheque"/>.</summary>
    [StringLength(20)]
    public string? StatutCheque { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    public string? Note { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public DateTime? DateModification { get; set; }
}
