using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FourniProApi.Models;

/// <summary>Payment methods accepted for a sale.</summary>
public enum PaymentMethod
{
    TPE,
    Virement,
    Especes
}

public class Vente
{
    [Key]
    public int VenteId { get; set; }

    /// <summary>Auto-generated by the API: VNT-{yyyyMMdd}-{id:D5}</summary>
    [StringLength(30)]
    public string? NumeroVente { get; set; }

    public DateOnly DateVente { get; set; }

    // ── FKs ──────────────────────────────────────────────────────────────────

    public int? ProduitID { get; set; }
    public int? ClientID { get; set; }

    public int? VoyageID { get; set; }

    public int? EmployeId { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────────

    public virtual Voyage? Voyage { get; set; }
    public virtual Employe? Employe { get; set; }

    // ── Financial ─────────────────────────────────────────────────────────────

    public int? Quantite { get; set; }

    [Column(TypeName = "decimal(18,2)")]
    public decimal? PrixUnitaire { get; set; }

    /// <summary>Discount amount applied to the total.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? Remise { get; set; }

    /// <summary>Computed and stored: PrixUnitaire * Quantite - Remise.</summary>
    [Column(TypeName = "decimal(18,2)")]
    public decimal? MontantTotal { get; set; }

    // ── Payment ───────────────────────────────────────────────────────────────

    [StringLength(20)]
    public string? PaymentMethod { get; set; }

    // ── Metadata ──────────────────────────────────────────────────────────────

    [StringLength(500)]
    public string? Note { get; set; }

    [StringLength(100)]
    public string? Reference { get; set; }

    /// <summary>File path or URL of the attached reference document.</summary>
    [StringLength(500)]
    public string? ReferenceFile { get; set; }

    // ── Audit ─────────────────────────────────────────────────────────────────

    public int? AjoutePar { get; set; }
    public DateTime? DateCreation { get; set; }
    public int? ModifiePar { get; set; }
    public DateTime? DateModification { get; set; }
}
