// <auto-generated />
using System;
using FourniProApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FourniProApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616183553_AddCreditFournisseur")]
    partial class AddCreditFournisseur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FourniProApi.Models.Achat", b =>
                {
                    b.Property<int>("AchatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AchatId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Cout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurID")
                        .HasColumnType("integer");

                    b.Property<bool?>("LivraisonDefectueuse")
                        .HasColumnType("boolean");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("PrixAchatUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int?>("VoyageID")
                        .HasColumnType("integer");

                    b.HasKey("AchatId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VoyageID");

                    b.ToTable("Achats");
                });

            modelBuilder.Entity("FourniProApi.Models.Avoir", b =>
                {
                    b.Property<int>("AvoirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvoirId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreditId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateAvoir")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontantAvoir")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroAvoir")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Raison")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ReferenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("VenteId")
                        .HasColumnType("integer");

                    b.HasKey("AvoirId");

                    b.HasIndex("CreditId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VenteId");

                    b.ToTable("Avoirs");
                });

            modelBuilder.Entity("FourniProApi.Models.Camion", b =>
                {
                    b.Property<int>("CamionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CamionId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<double?>("Consommation")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Kilometrage")
                        .HasColumnType("double precision");

                    b.Property<string>("Marque")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Matricule")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.HasKey("CamionId");

                    b.ToTable("Camions");
                });

            modelBuilder.Entity("FourniProApi.Models.Chauffeur", b =>
                {
                    b.Property<int>("ChauffeurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChauffeurId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroPermis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ChauffeurId");

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("FourniProApi.Models.Citerne", b =>
                {
                    b.Property<int>("CiterneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiterneId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Capacite")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MatriculeCiterne")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<int?>("PartitionsNumber")
                        .HasColumnType("integer");

                    b.HasKey("CiterneId");

                    b.ToTable("Citernes");
                });

            modelBuilder.Entity("FourniProApi.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Contact")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroClient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Personel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FourniProApi.Models.Credit", b =>
                {
                    b.Property<int>("CreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("ChequeReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateCredit")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCredit")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatutCheque")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("VoyageID")
                        .HasColumnType("integer");

                    b.HasKey("CreditId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VoyageID");

                    b.ToTable("Credits");
                });

            modelBuilder.Entity("FourniProApi.Models.CreditFournisseur", b =>
                {
                    b.Property<int>("CreditFournisseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreditFournisseurId"));

                    b.Property<int?>("AchatId")
                        .HasColumnType("integer");

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("ChequeReference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateCredit")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("NumeroCreditF")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatutCheque")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CreditFournisseurId");

                    b.HasIndex("AchatId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("FournisseurId");

                    b.ToTable("CreditsFournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("CIN")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Poste")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("Salaire")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("EmployeId");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("FourniProApi.Models.Fournisseur", b =>
                {
                    b.Property<int>("FournisseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FournisseurId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionsPaiement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Contact")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RIB")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Societe")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FournisseurId");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("FourniProApi.Models.FraisVoyage", b =>
                {
                    b.Property<int>("FraisVoyageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FraisVoyageId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("VoyageId")
                        .HasColumnType("integer");

                    b.HasKey("FraisVoyageId");

                    b.HasIndex("VoyageId");

                    b.ToTable("FraisVoyages");
                });

            modelBuilder.Entity("FourniProApi.Models.PaiementCredit", b =>
                {
                    b.Property<int>("PaiementCreditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaiementCreditId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int>("CreditId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DatePaiement")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PaiementCreditId");

                    b.HasIndex("CreditId");

                    b.HasIndex("EmployeId");

                    b.ToTable("PaiementsCredit");
                });

            modelBuilder.Entity("FourniProApi.Models.PaiementFournisseur", b =>
                {
                    b.Property<int>("PaiementFournisseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaiementFournisseurId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int>("CreditFournisseurId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DatePaiement")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PaiementFournisseurId");

                    b.HasIndex("CreditFournisseurId");

                    b.HasIndex("EmployeId");

                    b.ToTable("PaiementsFournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PermissionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("FourniProApi.Models.Produit", b =>
                {
                    b.Property<int>("ProduitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProduitId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DelaiDeLivraison")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroProduit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("PrixAchat")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrixHT")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrixTTC")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("integer");

                    b.Property<int?>("StockMinimum")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TVA")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProduitId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("FourniProApi.Models.StockVoyage", b =>
                {
                    b.Property<int>("StockVoyageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StockVoyageId"));

                    b.Property<int?>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<int>("VoyageId")
                        .HasColumnType("integer");

                    b.HasKey("StockVoyageId");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VoyageId");

                    b.ToTable("StockVoyages");
                });

            modelBuilder.Entity("FourniProApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            Email = "admin",
                            IsActive = true,
                            IsAdmin = true,
                            IsSuperAdmin = true,
                            Name = "admin",
                            Password = "1234",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = 1
                        });
                });

            modelBuilder.Entity("FourniProApi.Models.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("FourniProApi.Models.Vente", b =>
                {
                    b.Property<int>("VenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VenteId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateVente")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NumeroVente")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("PrixUnitaire")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProduitID")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReferenceFile")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Remise")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoyageID")
                        .HasColumnType("integer");

                    b.HasKey("VenteId");

                    b.HasIndex("EmployeId");

                    b.HasIndex("VoyageID");

                    b.ToTable("Ventes");
                });

            modelBuilder.Entity("FourniProApi.Models.Voyage", b =>
                {
                    b.Property<int>("VoyageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VoyageId"));

                    b.Property<int?>("AjoutePar")
                        .HasColumnType("integer");

                    b.Property<int?>("CamionId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChauffeurId")
                        .HasColumnType("integer");

                    b.Property<int?>("CiterneId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDepart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFinal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("KilometrageDepart")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("KilometrageFinal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LieuDepart")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LieuTerminal")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ModifiePar")
                        .HasColumnType("integer");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("VoyageId");

                    b.HasIndex("CamionId");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("CiterneId");

                    b.ToTable("Voyages");
                });

            modelBuilder.Entity("FourniProApi.Models.Achat", b =>
                {
                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("Achats")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("FourniProApi.Models.Avoir", b =>
                {
                    b.HasOne("FourniProApi.Models.Credit", "Credit")
                        .WithMany("Avoirs")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("Avoirs")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Vente", "Vente")
                        .WithMany("Avoirs")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Credit");

                    b.Navigation("Employe");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("FourniProApi.Models.Credit", b =>
                {
                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("Credits")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("FourniProApi.Models.CreditFournisseur", b =>
                {
                    b.HasOne("FourniProApi.Models.Achat", "Achat")
                        .WithMany("CreditsFournisseur")
                        .HasForeignKey("AchatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("CreditsFournisseur")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Fournisseur", "Fournisseur")
                        .WithMany("CreditsFournisseur")
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Achat");

                    b.Navigation("Employe");

                    b.Navigation("Fournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.FraisVoyage", b =>
                {
                    b.HasOne("FourniProApi.Models.Voyage", "Voyage")
                        .WithMany("Frais")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("FourniProApi.Models.PaiementCredit", b =>
                {
                    b.HasOne("FourniProApi.Models.Credit", "Credit")
                        .WithMany("PaiementsCredit")
                        .HasForeignKey("CreditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("PaiementsCredit")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Credit");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("FourniProApi.Models.PaiementFournisseur", b =>
                {
                    b.HasOne("FourniProApi.Models.CreditFournisseur", "CreditFournisseur")
                        .WithMany("PaiementsFournisseur")
                        .HasForeignKey("CreditFournisseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("PaiementsFournisseur")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreditFournisseur");

                    b.Navigation("Employe");
                });

            modelBuilder.Entity("FourniProApi.Models.StockVoyage", b =>
                {
                    b.HasOne("FourniProApi.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId");

                    b.HasOne("FourniProApi.Models.Voyage", "Voyage")
                        .WithMany("Stocks")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("FourniProApi.Models.UserPermission", b =>
                {
                    b.HasOne("FourniProApi.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FourniProApi.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FourniProApi.Models.Vente", b =>
                {
                    b.HasOne("FourniProApi.Models.Employe", "Employe")
                        .WithMany("Ventes")
                        .HasForeignKey("EmployeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Voyage", "Voyage")
                        .WithMany()
                        .HasForeignKey("VoyageID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employe");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("FourniProApi.Models.Voyage", b =>
                {
                    b.HasOne("FourniProApi.Models.Camion", "Camion")
                        .WithMany()
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Chauffeur", "Chauffeur")
                        .WithMany()
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FourniProApi.Models.Citerne", "Citerne")
                        .WithMany()
                        .HasForeignKey("CiterneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Camion");

                    b.Navigation("Chauffeur");

                    b.Navigation("Citerne");
                });

            modelBuilder.Entity("FourniProApi.Models.Achat", b =>
                {
                    b.Navigation("CreditsFournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.Credit", b =>
                {
                    b.Navigation("Avoirs");

                    b.Navigation("PaiementsCredit");
                });

            modelBuilder.Entity("FourniProApi.Models.CreditFournisseur", b =>
                {
                    b.Navigation("PaiementsFournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.Employe", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Avoirs");

                    b.Navigation("Credits");

                    b.Navigation("CreditsFournisseur");

                    b.Navigation("PaiementsCredit");

                    b.Navigation("PaiementsFournisseur");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("FourniProApi.Models.Fournisseur", b =>
                {
                    b.Navigation("CreditsFournisseur");
                });

            modelBuilder.Entity("FourniProApi.Models.Permission", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FourniProApi.Models.User", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FourniProApi.Models.Vente", b =>
                {
                    b.Navigation("Avoirs");
                });

            modelBuilder.Entity("FourniProApi.Models.Voyage", b =>
                {
                    b.Navigation("Frais");

                    b.Navigation("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
