CREATE TABLE "Categories" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(100) NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("ID")
);


CREATE TABLE "Clients" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroClient" character varying(20) NOT NULL,
    "Nom" character varying(100) NOT NULL,
    "Contact" character varying(100),
    "CIN" character varying(100) NOT NULL,
    "NomSociete" character varying(100) NOT NULL,
    "userID" integer NOT NULL,
    "DateCreation" timestamp with time zone NOT NULL,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("ID")
);


CREATE TABLE "DepenseCategories" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreePar" character varying(50),
    "DateCreation" timestamp with time zone,
    "ModifiePar" character varying(50),
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_DepenseCategories" PRIMARY KEY ("ID")
);


CREATE TABLE "Depenses" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" character varying(20),
    "Date" date,
    "Categorie" character varying(100),
    "Montant" numeric(10,2),
    "Description" character varying(500),
    "CreePar" character varying(50),
    "DateCreation" timestamp with time zone,
    "ModifiePar" character varying(50),
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Depenses" PRIMARY KEY ("ID")
);


CREATE TABLE "Employes" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(50) NOT NULL,
    "Prenom" character varying(50) NOT NULL,
    "CIN" character varying(20) NOT NULL,
    "Telephone" character varying(15),
    "Address" character varying(200) NOT NULL,
    "Poste" character varying(100),
    "Salaire" numeric(10,2),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Employes" PRIMARY KEY ("ID")
);


CREATE TABLE "Fournisseurs" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Prenom" character varying(50),
    "Nom" character varying(50),
    "Societe" character varying(50),
    "Adresse" character varying(200),
    "Telephone" character varying(20),
    "Email" character varying(100),
    "RIB" character varying(30),
    "Contact" character varying(50),
    "ConditionsPaiement" character varying(50),
    "Statut" character varying(50) NOT NULL,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Fournisseurs" PRIMARY KEY ("ID")
);


CREATE TABLE "IndicateursFinanciers" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "DebutPeriode" date,
    "FinPeriode" date,
    "ChiffreAffairesTotal" numeric(12,2),
    "DepensesTotales" numeric(12,2),
    "BeneficeNet" numeric(12,2),
    "TotalAchats" numeric(12,2),
    "TotalVentes" numeric(12,2),
    "TotalCarburantVendu" numeric(12,2),
    "TotalProduitsVendus" numeric(12,2),
    "TotalServicesVendus" numeric(12,2),
    "DateCreation" timestamp with time zone,
    CONSTRAINT "PK_IndicateursFinanciers" PRIMARY KEY ("ID")
);


CREATE TABLE "JoursActivité" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Date" date NOT NULL,
    "ChiffreAffaires" numeric(12,2),
    "FraisExploitation" numeric(12,2),
    CONSTRAINT "PK_JoursActivité" PRIMARY KEY ("ID")
);


CREATE TABLE "MoyensPaiement" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(50),
    CONSTRAINT "PK_MoyensPaiement" PRIMARY KEY ("ID")
);


CREATE TABLE "ServiceCategories" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IsActive" boolean NOT NULL,
    "CreePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_ServiceCategories" PRIMARY KEY ("ID")
);


CREATE TABLE "StationInfos" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "StationName" character varying(200) NOT NULL,
    "Adresse" character varying(500),
    "Ville" character varying(100),
    "TP" character varying(50),
    "IF" character varying(50),
    "RC" character varying(50),
    "CNSS" character varying(50),
    "ICE" character varying(50),
    "Tel" character varying(30),
    "Fax" character varying(30),
    "SiteWeb" character varying(200),
    "Email" character varying(100),
    "Logo" bytea,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_StationInfos" PRIMARY KEY ("ID")
);


CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "IsSuperAdmin" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "createdBy" integer NOT NULL,
    "updatedBy" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CanManageUsers" boolean NOT NULL,
    "CanManageProducts" boolean NOT NULL,
    "CanViewReports" boolean NOT NULL,
    "CanManageSettings" boolean NOT NULL,
    "CanManageSales" boolean NOT NULL,
    "CanManagePromotions" boolean NOT NULL,
    "CanManageCustomers" boolean NOT NULL,
    "CanManageSuppliers" boolean NOT NULL,
    "CanManageCategories" boolean NOT NULL,
    "ShowAcceuil" boolean NOT NULL,
    "ShowTableauDeBord" boolean NOT NULL,
    "ShowVente" boolean NOT NULL,
    "EditLivreur" boolean NOT NULL,
    "AddAchat" boolean NOT NULL,
    "EditCiternes" boolean NOT NULL,
    "EditPistolets" boolean NOT NULL,
    "EditClients" boolean NOT NULL,
    "AddBonFacturation" boolean NOT NULL,
    "ShowDepenses" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);


CREATE TABLE "Produits" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroProduit" character varying(20) NOT NULL,
    "Description" character varying(255),
    "PrixAchat" numeric(10,2),
    "PrixHT" numeric(10,2),
    "TVA" numeric(5,2),
    "PrixTTC" numeric(10,2),
    "Stock" integer,
    "StockMinimum" integer,
    "DelaiDeLivraison" integer,
    "CategorieID" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Produits" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Produits_Categories_CategorieID" FOREIGN KEY ("CategorieID") REFERENCES "Categories" ("ID")
);


CREATE TABLE "BilansCredit" (
    "BilanID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "TotalCredit" numeric(12,2) NOT NULL,
    "TotalPaye" numeric(12,2) NOT NULL,
    "Balance" numeric(12,2) NOT NULL,
    "CreditFacture" numeric(12,2) NOT NULL,
    "CreditNonFacture" numeric(12,2) NOT NULL,
    "DerniereMiseAJour" timestamp with time zone NOT NULL,
    "PeriodeDebut" timestamp with time zone,
    "PeriodeFin" timestamp with time zone,
    CONSTRAINT "PK_BilansCredit" PRIMARY KEY ("BilanID"),
    CONSTRAINT "FK_BilansCredit_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE
);


CREATE TABLE "BonsLivraison" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroBL" character varying(20) NOT NULL,
    "DateBL" date NOT NULL,
    "ClientID" integer NOT NULL,
    "MontantTotal" numeric(10,2) NOT NULL,
    "EstFacture" boolean NOT NULL,
    "Notes" character varying(255),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_BonsLivraison" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_BonsLivraison_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE RESTRICT
);


CREATE TABLE "EmployeBilanCredits" (
    "BilanID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeID" integer NOT NULL,
    "TotalCredit" numeric(12,2) NOT NULL,
    "TotalPaye" numeric(12,2) NOT NULL,
    "Balance" numeric(12,2) NOT NULL,
    CONSTRAINT "PK_EmployeBilanCredits" PRIMARY KEY ("BilanID"),
    CONSTRAINT "FK_EmployeBilanCredits_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID") ON DELETE CASCADE
);


CREATE TABLE "EmployeCreditTransactions" (
    "CreditID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroTransaction" character varying(20),
    "EmployeID" integer NOT NULL,
    "MontantTotal" numeric(10,2) NOT NULL,
    "DateCredit" timestamp with time zone NOT NULL,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_EmployeCreditTransactions" PRIMARY KEY ("CreditID"),
    CONSTRAINT "FK_EmployeCreditTransactions_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Jaugeages" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "DateJaugeage" timestamp with time zone NOT NULL,
    "TemoinID" integer NOT NULL,
    "NumeroJaugeage" character varying(50),
    "Observations" character varying(500),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Jaugeages" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Jaugeages_Employes_TemoinID" FOREIGN KEY ("TemoinID") REFERENCES "Employes" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Periodes" (
    "PeriodeID" integer GENERATED BY DEFAULT AS IDENTITY,
    "DateDebut" timestamp with time zone NOT NULL,
    "DateFin" timestamp with time zone NOT NULL,
    "EmployeID" integer,
    "TPE" numeric(18,2) NOT NULL,
    "Especes" numeric(18,2) NOT NULL,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Periodes" PRIMARY KEY ("PeriodeID"),
    CONSTRAINT "FK_Periodes_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID")
);


CREATE TABLE "Chauffeurs" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(50) NOT NULL,
    "Prenom" character varying(50),
    "CIN" character varying(20),
    "Telephone" character varying(20),
    "NumeroPermis" character varying(50),
    "FournisseurID" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Chauffeurs" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Chauffeurs_Fournisseurs_FournisseurID" FOREIGN KEY ("FournisseurID") REFERENCES "Fournisseurs" ("ID")
);


CREATE TABLE "Citernes" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "MatriculeCiterne" character varying(50),
    "Capacite" numeric(10,2),
    "PartitionsNumber" bigint,
    "FournisseurID" integer NOT NULL,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Citernes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Citernes_Fournisseurs_FournisseurID" FOREIGN KEY ("FournisseurID") REFERENCES "Fournisseurs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "EmployeReglementCredits" (
    "ReglementID" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeID" integer NOT NULL,
    "MontantPaye" numeric(10,2) NOT NULL,
    "ModePaiementID" integer NOT NULL,
    "ReferenceTransaction" character varying(50),
    "ValidePar" character varying(100),
    "DateReglement" timestamp with time zone NOT NULL,
    "Remarques" character varying(500),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_EmployeReglementCredits" PRIMARY KEY ("ReglementID"),
    CONSTRAINT "FK_EmployeReglementCredits_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_EmployeReglementCredits_MoyensPaiement_ModePaiementID" FOREIGN KEY ("ModePaiementID") REFERENCES "MoyensPaiement" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Factures" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroFacture" character varying(20),
    "DateFacture" date,
    "ClientID" integer,
    "MontantTotal" numeric(10,2),
    "Statut" character varying(50),
    "MoyenPaiementID" integer,
    "DatePaiement" date,
    CONSTRAINT "PK_Factures" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Factures_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_Factures_MoyensPaiement_MoyenPaiementID" FOREIGN KEY ("MoyenPaiementID") REFERENCES "MoyensPaiement" ("ID")
);


CREATE TABLE "ReglementsCredit" (
    "ReglementID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ClientID" integer NOT NULL,
    "MontantPaye" numeric(10,2) NOT NULL,
    "ModePaiementID" integer NOT NULL,
    "ReferenceTransaction" character varying(50),
    "ValidePar" character varying(100),
    "DateReglement" timestamp with time zone NOT NULL,
    "Remarques" character varying(500),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_ReglementsCredit" PRIMARY KEY ("ReglementID"),
    CONSTRAINT "FK_ReglementsCredit_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_ReglementsCredit_MoyensPaiement_ModePaiementID" FOREIGN KEY ("ModePaiementID") REFERENCES "MoyensPaiement" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Services" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" character varying(20),
    "Description" character varying(255),
    "Prix" numeric(10,2),
    "ServiceCategorieID" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Services" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Services_ServiceCategories_ServiceCategorieID" FOREIGN KEY ("ServiceCategorieID") REFERENCES "ServiceCategories" ("ID")
);


CREATE TABLE "DepotsCaisse" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Montant" numeric(18,2) NOT NULL,
    "DateDepot" timestamp with time zone NOT NULL,
    "ReferenceBancaire" character varying(100),
    "Banque" character varying(200),
    "Notes" character varying(500),
    "PieceJustificativeNom" character varying(255),
    "PieceJustificativeBase64" text,
    "PieceJustificativeType" character varying(100),
    "ValidePar" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_DepotsCaisse" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_DepotsCaisse_Users_ValidePar" FOREIGN KEY ("ValidePar") REFERENCES "Users" ("UserId")
);


CREATE TABLE "Reservoirs" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" character varying(20) NOT NULL,
    "ProduitID" integer,
    "Capacite" numeric(10,2) NOT NULL,
    "NiveauDeCarburant" numeric(10,2) NOT NULL,
    "HauteurMax" numeric(6,2),
    "Fabricant" character varying(100),
    "NumeroSerie" character varying(50),
    "DiametreMm" numeric(8,2),
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Reservoirs" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Reservoirs_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID")
);


CREATE TABLE "VenteLubrifiantsEtArticles" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroVente" character varying(20),
    "DateVente" timestamp with time zone NOT NULL,
    "ProduitID" integer NOT NULL,
    "QuantiteVendue" integer NOT NULL,
    "PrixUnitaireTTC" numeric(10,2) NOT NULL,
    "ClientID" integer,
    "EmployeID" integer,
    "MoyenPaiementID" integer,
    "Notes" character varying(500),
    "Statut" character varying(50),
    "DateCreation" timestamp with time zone,
    "DateModification" timestamp with time zone,
    "CreePar" character varying(50),
    "ModifiePar" character varying(50),
    CONSTRAINT "PK_VenteLubrifiantsEtArticles" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_VenteLubrifiantsEtArticles_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_VenteLubrifiantsEtArticles_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID"),
    CONSTRAINT "FK_VenteLubrifiantsEtArticles_MoyensPaiement_MoyenPaiementID" FOREIGN KEY ("MoyenPaiementID") REFERENCES "MoyensPaiement" ("ID"),
    CONSTRAINT "FK_VenteLubrifiantsEtArticles_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Camions" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Matricule" character varying(20),
    "Marque" character varying(50),
    "CiterneID" integer,
    "FournisseurID" integer NOT NULL,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Camions" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Camions_Citernes_CiterneID" FOREIGN KEY ("CiterneID") REFERENCES "Citernes" ("ID"),
    CONSTRAINT "FK_Camions_Fournisseurs_FournisseurID" FOREIGN KEY ("FournisseurID") REFERENCES "Fournisseurs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "FactureBonLivraisons" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FactureID" integer NOT NULL,
    "BonLivraisonID" integer NOT NULL,
    "DateAssociation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_FactureBonLivraisons" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_FactureBonLivraisons_BonsLivraison_BonLivraisonID" FOREIGN KEY ("BonLivraisonID") REFERENCES "BonsLivraison" ("ID") ON DELETE RESTRICT,
    CONSTRAINT "FK_FactureBonLivraisons_Factures_FactureID" FOREIGN KEY ("FactureID") REFERENCES "Factures" ("ID") ON DELETE CASCADE
);


CREATE TABLE "BonLivraisonDetails" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "BonLivraisonID" integer NOT NULL,
    "ProduitID" integer,
    "ServiceID" integer,
    "Quantite" integer NOT NULL,
    "PrixUnitaire" numeric(10,2) NOT NULL,
    "MontantLigne" numeric(10,2) NOT NULL,
    "Description" character varying(255),
    CONSTRAINT "PK_BonLivraisonDetails" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_BonLivraisonDetails_BonsLivraison_BonLivraisonID" FOREIGN KEY ("BonLivraisonID") REFERENCES "BonsLivraison" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_BonLivraisonDetails_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID") ON DELETE RESTRICT,
    CONSTRAINT "FK_BonLivraisonDetails_Services_ServiceID" FOREIGN KEY ("ServiceID") REFERENCES "Services" ("ID") ON DELETE RESTRICT
);


CREATE TABLE "CreditTransactions" (
    "CreditID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroTransaction" character varying(20),
    "ClientID" integer NOT NULL,
    "ProduitID" integer,
    "ServiceID" integer,
    "PrixTTC" numeric(10,2) NOT NULL,
    "Quantite" integer NOT NULL,
    "MontantTotal" numeric(10,2) NOT NULL,
    "DateCredit" timestamp with time zone NOT NULL,
    "Facture" boolean NOT NULL,
    "FactureID" integer,
    "BonLivraisonID" integer,
    "EstEnBL" boolean NOT NULL,
    "PeriodeID" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_CreditTransactions" PRIMARY KEY ("CreditID"),
    CONSTRAINT "FK_CreditTransactions_BonsLivraison_BonLivraisonID" FOREIGN KEY ("BonLivraisonID") REFERENCES "BonsLivraison" ("ID") ON DELETE SET NULL,
    CONSTRAINT "FK_CreditTransactions_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_CreditTransactions_Factures_FactureID" FOREIGN KEY ("FactureID") REFERENCES "Factures" ("ID"),
    CONSTRAINT "FK_CreditTransactions_Periodes_PeriodeID" FOREIGN KEY ("PeriodeID") REFERENCES "Periodes" ("PeriodeID") ON DELETE SET NULL,
    CONSTRAINT "FK_CreditTransactions_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID"),
    CONSTRAINT "FK_CreditTransactions_Services_ServiceID" FOREIGN KEY ("ServiceID") REFERENCES "Services" ("ID")
);


CREATE TABLE "ÉlémentsFacture" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "FactureID" integer,
    "ProduitID" integer,
    "ServiceID" integer,
    "Quantite" integer,
    "PrixUnitaire" numeric(10,2),
    CONSTRAINT "PK_ÉlémentsFacture" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ÉlémentsFacture_Factures_FactureID" FOREIGN KEY ("FactureID") REFERENCES "Factures" ("ID"),
    CONSTRAINT "FK_ÉlémentsFacture_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID"),
    CONSTRAINT "FK_ÉlémentsFacture_Services_ServiceID" FOREIGN KEY ("ServiceID") REFERENCES "Services" ("ID")
);


CREATE TABLE "VenteServices" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "NumeroVente" character varying(20),
    "DateVente" timestamp with time zone NOT NULL,
    "ServiceID" integer NOT NULL,
    "Quantite" integer NOT NULL,
    "PrixUnitaire" numeric(10,2) NOT NULL,
    "ClientID" integer,
    "EmployeID" integer,
    "MoyenPaiementID" integer,
    "Notes" character varying(500),
    "Statut" character varying(50),
    "DateCreation" timestamp with time zone,
    "DateModification" timestamp with time zone,
    "CreePar" integer,
    "ModifiePar" integer,
    CONSTRAINT "PK_VenteServices" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_VenteServices_Clients_ClientID" FOREIGN KEY ("ClientID") REFERENCES "Clients" ("ID"),
    CONSTRAINT "FK_VenteServices_Employes_EmployeID" FOREIGN KEY ("EmployeID") REFERENCES "Employes" ("ID"),
    CONSTRAINT "FK_VenteServices_MoyensPaiement_MoyenPaiementID" FOREIGN KEY ("MoyenPaiementID") REFERENCES "MoyensPaiement" ("ID"),
    CONSTRAINT "FK_VenteServices_Services_ServiceID" FOREIGN KEY ("ServiceID") REFERENCES "Services" ("ID") ON DELETE CASCADE
);


CREATE TABLE "JaugeageDetails" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "JaugeageID" integer NOT NULL,
    "ReservoirID" integer NOT NULL,
    "HauteurMesuree" numeric(10,2) NOT NULL,
    "VolumeCalcule" numeric(10,2) NOT NULL,
    "Temperature" numeric(10,2),
    "Notes" character varying(500),
    CONSTRAINT "PK_JaugeageDetails" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_JaugeageDetails_Jaugeages_JaugeageID" FOREIGN KEY ("JaugeageID") REFERENCES "Jaugeages" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_JaugeageDetails_Reservoirs_ReservoirID" FOREIGN KEY ("ReservoirID") REFERENCES "Reservoirs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Pompes" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" character varying(20) NOT NULL,
    "Statut" character varying(50) NOT NULL,
    "CompteurElectroniqueActuel" numeric(18,3),
    "CompteurMecaniqueActuel" numeric(18,3),
    "ReservoirAssocieID" integer,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Pompes" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Pompes_Reservoirs_ReservoirAssocieID" FOREIGN KEY ("ReservoirAssocieID") REFERENCES "Reservoirs" ("ID")
);


CREATE TABLE "ReservoirCalibrations" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReservoirID" integer NOT NULL,
    "HauteurCm" numeric(6,2) NOT NULL,
    "VolumeLitres" numeric(12,2) NOT NULL,
    CONSTRAINT "PK_ReservoirCalibrations" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ReservoirCalibrations_Reservoirs_ReservoirID" FOREIGN KEY ("ReservoirID") REFERENCES "Reservoirs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "Achats" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Numero" character varying(20),
    "Date" date NOT NULL,
    "FournisseurID" integer,
    "ProduitID" integer,
    "Quantite" integer,
    "Cout" numeric(10,2),
    "PrixAchatUnitaire" numeric(10,2),
    "ChauffeurID" integer,
    "CamionID" integer,
    "LivraisonDefectueuse" boolean,
    "AjoutePar" integer,
    "DateCreation" timestamp with time zone,
    "ModifiePar" integer,
    "DateModification" timestamp with time zone,
    CONSTRAINT "PK_Achats" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_Achats_Camions_CamionID" FOREIGN KEY ("CamionID") REFERENCES "Camions" ("ID"),
    CONSTRAINT "FK_Achats_Chauffeurs_ChauffeurID" FOREIGN KEY ("ChauffeurID") REFERENCES "Chauffeurs" ("ID"),
    CONSTRAINT "FK_Achats_Fournisseurs_FournisseurID" FOREIGN KEY ("FournisseurID") REFERENCES "Fournisseurs" ("ID"),
    CONSTRAINT "FK_Achats_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID")
);


CREATE TABLE "PeriodeDetails" (
    "PeriodeDetailID" integer GENERATED BY DEFAULT AS IDENTITY,
    "PeriodeID" integer NOT NULL,
    "PompeID" integer NOT NULL,
    "ReservoirID" integer NOT NULL,
    "ProduitID" integer NOT NULL,
    "PrixCarburant" numeric(10,2) NOT NULL,
    "CompteurElectroniqueDebut" numeric NOT NULL,
    "CompteurElectroniqueFinal" numeric NOT NULL,
    "CompteurMecaniqueDebut" numeric NOT NULL,
    "CompteurMecaniqueFinal" numeric NOT NULL,
    CONSTRAINT "PK_PeriodeDetails" PRIMARY KEY ("PeriodeDetailID"),
    CONSTRAINT "FK_PeriodeDetails_Periodes_PeriodeID" FOREIGN KEY ("PeriodeID") REFERENCES "Periodes" ("PeriodeID") ON DELETE CASCADE,
    CONSTRAINT "FK_PeriodeDetails_Pompes_PompeID" FOREIGN KEY ("PompeID") REFERENCES "Pompes" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_PeriodeDetails_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_PeriodeDetails_Reservoirs_ReservoirID" FOREIGN KEY ("ReservoirID") REFERENCES "Reservoirs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "AchatAllocations" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "AchatID" integer NOT NULL,
    "ReservoirID" integer NOT NULL,
    "QuantiteAllouee" numeric(10,2) NOT NULL,
    "DateAllocation" timestamp with time zone NOT NULL,
    "Notes" character varying(500),
    "Statut" character varying(50) NOT NULL,
    "UtilisateurAllocation" character varying(100),
    CONSTRAINT "PK_AchatAllocations" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_AchatAllocations_Achats_AchatID" FOREIGN KEY ("AchatID") REFERENCES "Achats" ("ID") ON DELETE CASCADE,
    CONSTRAINT "FK_AchatAllocations_Reservoirs_ReservoirID" FOREIGN KEY ("ReservoirID") REFERENCES "Reservoirs" ("ID") ON DELETE CASCADE
);


CREATE TABLE "StockLots" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL DEFAULT 1,
    "AchatID" integer,
    "ReservoirID" integer NOT NULL,
    "ProduitID" integer NOT NULL,
    "QuantiteInitiale" numeric(12,3) NOT NULL,
    "QuantiteDisponible" numeric(12,3) NOT NULL,
    "PrixAchat" numeric(10,2) NOT NULL,
    "DateEntree" timestamp with time zone NOT NULL,
    "Statut" character varying(20) NOT NULL,
    "Notes" character varying(500),
    CONSTRAINT "PK_StockLots" PRIMARY KEY ("ID"),
    CONSTRAINT "CK_StockLots_AchatID_Type_Consistency" CHECK (("Type" = 1 AND "AchatID" IS NOT NULL) OR ("Type" != 1 AND "AchatID" IS NULL)),
    CONSTRAINT "CK_StockLots_PrixAchat_NonNegative" CHECK ("PrixAchat" >= 0),
    CONSTRAINT "CK_StockLots_QuantiteDisponible_Bounds" CHECK ("QuantiteDisponible" >= 0 AND "QuantiteDisponible" <= "QuantiteInitiale"),
    CONSTRAINT "CK_StockLots_QuantiteInitiale_Positive" CHECK ("QuantiteInitiale" > 0),
    CONSTRAINT "FK_StockLots_Achats_AchatID" FOREIGN KEY ("AchatID") REFERENCES "Achats" ("ID") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockLots_Produits_ProduitID" FOREIGN KEY ("ProduitID") REFERENCES "Produits" ("ID") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockLots_Reservoirs_ReservoirID" FOREIGN KEY ("ReservoirID") REFERENCES "Reservoirs" ("ID") ON DELETE RESTRICT
);


CREATE TABLE "StockLotConsumptions" (
    "ID" integer GENERATED BY DEFAULT AS IDENTITY,
    "StockLotID" integer NOT NULL,
    "PeriodeDetailID" integer NOT NULL,
    "QuantiteConsommee" numeric(12,3) NOT NULL,
    "PrixUnitaire" numeric(10,2) NOT NULL,
    "DateConsommation" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_StockLotConsumptions" PRIMARY KEY ("ID"),
    CONSTRAINT "CK_StockLotConsumptions_PrixUnitaire_NonNegative" CHECK ("PrixUnitaire" >= 0),
    CONSTRAINT "CK_StockLotConsumptions_QuantiteConsommee_Positive" CHECK ("QuantiteConsommee" > 0),
    CONSTRAINT "FK_StockLotConsumptions_PeriodeDetails_PeriodeDetailID" FOREIGN KEY ("PeriodeDetailID") REFERENCES "PeriodeDetails" ("PeriodeDetailID") ON DELETE CASCADE,
    CONSTRAINT "FK_StockLotConsumptions_StockLots_StockLotID" FOREIGN KEY ("StockLotID") REFERENCES "StockLots" ("ID") ON DELETE RESTRICT
);


INSERT INTO "Categories" ("ID", "Nom")
VALUES (1, 'CARBURANT');
INSERT INTO "Categories" ("ID", "Nom")
VALUES (2, 'LUBRIFIANT');
INSERT INTO "Categories" ("ID", "Nom")
VALUES (3, 'ARTICLE');


INSERT INTO "MoyensPaiement" ("ID", "Nom")
VALUES (1, 'Espèces');
INSERT INTO "MoyensPaiement" ("ID", "Nom")
VALUES (2, 'TPE');
INSERT INTO "MoyensPaiement" ("ID", "Nom")
VALUES (3, 'Chèque');


INSERT INTO "Users" ("UserId", "AddAchat", "AddBonFacturation", "CanManageCategories", "CanManageCustomers", "CanManageProducts", "CanManagePromotions", "CanManageSales", "CanManageSettings", "CanManageSuppliers", "CanManageUsers", "CanViewReports", "CreatedAt", "EditCiternes", "EditClients", "EditLivreur", "EditPistolets", "Email", "IsActive", "IsAdmin", "IsSuperAdmin", "Name", "Password", "ShowAcceuil", "ShowDepenses", "ShowTableauDeBord", "ShowVente", "UpdatedAt", "createdBy", "updatedBy")
VALUES (5, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TIMESTAMPTZ '2024-01-01T00:00:00Z', TRUE, TRUE, TRUE, TRUE, 'admin@bombapromax.com', TRUE, TRUE, FALSE, 'Admin User', 'Admin@123', TRUE, TRUE, TRUE, TRUE, TIMESTAMPTZ '2026-01-28T18:50:15.958683Z', 0, 0);
INSERT INTO "Users" ("UserId", "AddAchat", "AddBonFacturation", "CanManageCategories", "CanManageCustomers", "CanManageProducts", "CanManagePromotions", "CanManageSales", "CanManageSettings", "CanManageSuppliers", "CanManageUsers", "CanViewReports", "CreatedAt", "EditCiternes", "EditClients", "EditLivreur", "EditPistolets", "Email", "IsActive", "IsAdmin", "IsSuperAdmin", "Name", "Password", "ShowAcceuil", "ShowDepenses", "ShowTableauDeBord", "ShowVente", "UpdatedAt", "createdBy", "updatedBy")
VALUES (6, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TIMESTAMPTZ '2024-01-01T00:00:00Z', TRUE, TRUE, TRUE, TRUE, 'superadmin@bombapromax.com', TRUE, TRUE, TRUE, 'Super Admin', 'SuperAdmin@123', TRUE, TRUE, TRUE, TRUE, TIMESTAMPTZ '2026-01-28T18:50:15.958684Z', 0, 0);


CREATE INDEX "IX_AchatAllocations_AchatID" ON "AchatAllocations" ("AchatID");


CREATE INDEX "IX_AchatAllocations_ReservoirID" ON "AchatAllocations" ("ReservoirID");


CREATE INDEX "IX_Achats_CamionID" ON "Achats" ("CamionID");


CREATE INDEX "IX_Achats_ChauffeurID" ON "Achats" ("ChauffeurID");


CREATE INDEX "IX_Achats_FournisseurID" ON "Achats" ("FournisseurID");


CREATE INDEX "IX_Achats_ProduitID" ON "Achats" ("ProduitID");


CREATE UNIQUE INDEX "IX_BilansCredit_ClientID" ON "BilansCredit" ("ClientID");


CREATE INDEX "IX_BonLivraisonDetails_BonLivraisonID" ON "BonLivraisonDetails" ("BonLivraisonID");


CREATE INDEX "IX_BonLivraisonDetails_ProduitID" ON "BonLivraisonDetails" ("ProduitID");


CREATE INDEX "IX_BonLivraisonDetails_ServiceID" ON "BonLivraisonDetails" ("ServiceID");


CREATE INDEX "IX_BonsLivraison_ClientID" ON "BonsLivraison" ("ClientID");


CREATE UNIQUE INDEX "IX_BonsLivraison_NumeroBL" ON "BonsLivraison" ("NumeroBL");


CREATE INDEX "IX_Camions_CiterneID" ON "Camions" ("CiterneID");


CREATE INDEX "IX_Camions_FournisseurID" ON "Camions" ("FournisseurID");


CREATE INDEX "IX_Chauffeurs_FournisseurID" ON "Chauffeurs" ("FournisseurID");


CREATE INDEX "IX_Citernes_FournisseurID" ON "Citernes" ("FournisseurID");


CREATE UNIQUE INDEX "IX_Clients_CIN" ON "Clients" ("CIN");


CREATE UNIQUE INDEX "IX_Clients_NumeroClient" ON "Clients" ("NumeroClient");


CREATE INDEX "IX_CreditTransactions_BonLivraisonID" ON "CreditTransactions" ("BonLivraisonID");


CREATE INDEX "IX_CreditTransactions_ClientID" ON "CreditTransactions" ("ClientID");


CREATE INDEX "IX_CreditTransactions_FactureID" ON "CreditTransactions" ("FactureID");


CREATE INDEX "IX_CreditTransactions_PeriodeID" ON "CreditTransactions" ("PeriodeID");


CREATE INDEX "IX_CreditTransactions_ProduitID" ON "CreditTransactions" ("ProduitID");


CREATE INDEX "IX_CreditTransactions_ServiceID" ON "CreditTransactions" ("ServiceID");


CREATE INDEX "IX_DepotsCaisse_ValidePar" ON "DepotsCaisse" ("ValidePar");


CREATE INDEX "IX_ÉlémentsFacture_FactureID" ON "ÉlémentsFacture" ("FactureID");


CREATE INDEX "IX_ÉlémentsFacture_ProduitID" ON "ÉlémentsFacture" ("ProduitID");


CREATE INDEX "IX_ÉlémentsFacture_ServiceID" ON "ÉlémentsFacture" ("ServiceID");


CREATE UNIQUE INDEX "IX_EmployeBilanCredits_EmployeID" ON "EmployeBilanCredits" ("EmployeID");


CREATE INDEX "IX_EmployeCreditTransactions_EmployeID" ON "EmployeCreditTransactions" ("EmployeID");


CREATE INDEX "IX_EmployeReglementCredits_EmployeID" ON "EmployeReglementCredits" ("EmployeID");


CREATE INDEX "IX_EmployeReglementCredits_ModePaiementID" ON "EmployeReglementCredits" ("ModePaiementID");


CREATE UNIQUE INDEX "IX_FactureBonLivraisons_BonLivraisonID" ON "FactureBonLivraisons" ("BonLivraisonID");


CREATE INDEX "IX_FactureBonLivraisons_FactureID" ON "FactureBonLivraisons" ("FactureID");


CREATE INDEX "IX_Factures_ClientID" ON "Factures" ("ClientID");


CREATE INDEX "IX_Factures_MoyenPaiementID" ON "Factures" ("MoyenPaiementID");


CREATE INDEX "IX_JaugeageDetails_JaugeageID" ON "JaugeageDetails" ("JaugeageID");


CREATE INDEX "IX_JaugeageDetails_ReservoirID" ON "JaugeageDetails" ("ReservoirID");


CREATE INDEX "IX_Jaugeages_TemoinID" ON "Jaugeages" ("TemoinID");


CREATE INDEX "IX_PeriodeDetails_PeriodeID" ON "PeriodeDetails" ("PeriodeID");


CREATE INDEX "IX_PeriodeDetails_PompeID" ON "PeriodeDetails" ("PompeID");


CREATE INDEX "IX_PeriodeDetails_ProduitID" ON "PeriodeDetails" ("ProduitID");


CREATE INDEX "IX_PeriodeDetails_ReservoirID" ON "PeriodeDetails" ("ReservoirID");


CREATE INDEX "IX_Periodes_EmployeID" ON "Periodes" ("EmployeID");


CREATE INDEX "IX_Pompes_ReservoirAssocieID" ON "Pompes" ("ReservoirAssocieID");


CREATE INDEX "IX_Produits_CategorieID" ON "Produits" ("CategorieID");


CREATE INDEX "IX_ReglementsCredit_ClientID" ON "ReglementsCredit" ("ClientID");


CREATE INDEX "IX_ReglementsCredit_ModePaiementID" ON "ReglementsCredit" ("ModePaiementID");


CREATE UNIQUE INDEX "IX_ReservoirCalibrations_ReservoirID_HauteurCm" ON "ReservoirCalibrations" ("ReservoirID", "HauteurCm");


CREATE INDEX "IX_Reservoirs_ProduitID" ON "Reservoirs" ("ProduitID");


CREATE INDEX "IX_Services_ServiceCategorieID" ON "Services" ("ServiceCategorieID");


CREATE INDEX "IX_StockLotConsumptions_PeriodeDetailID" ON "StockLotConsumptions" ("PeriodeDetailID");


CREATE INDEX "IX_StockLotConsumptions_StockLotID" ON "StockLotConsumptions" ("StockLotID");


CREATE INDEX "IX_StockLots_AchatID" ON "StockLots" ("AchatID");


CREATE INDEX "IX_StockLots_ProduitID" ON "StockLots" ("ProduitID");


CREATE INDEX "IX_StockLots_ReservoirID_DateEntree_ID" ON "StockLots" ("ReservoirID", "DateEntree", "ID");


CREATE INDEX "IX_StockLots_ReservoirID_Statut" ON "StockLots" ("ReservoirID", "Statut");


CREATE INDEX "IX_StockLots_ReservoirID_Type" ON "StockLots" ("ReservoirID", "Type");


CREATE INDEX "IX_VenteLubrifiantsEtArticles_ClientID" ON "VenteLubrifiantsEtArticles" ("ClientID");


CREATE INDEX "IX_VenteLubrifiantsEtArticles_EmployeID" ON "VenteLubrifiantsEtArticles" ("EmployeID");


CREATE INDEX "IX_VenteLubrifiantsEtArticles_MoyenPaiementID" ON "VenteLubrifiantsEtArticles" ("MoyenPaiementID");


CREATE INDEX "IX_VenteLubrifiantsEtArticles_ProduitID" ON "VenteLubrifiantsEtArticles" ("ProduitID");


CREATE INDEX "IX_VenteServices_ClientID" ON "VenteServices" ("ClientID");


CREATE INDEX "IX_VenteServices_EmployeID" ON "VenteServices" ("EmployeID");


CREATE INDEX "IX_VenteServices_MoyenPaiementID" ON "VenteServices" ("MoyenPaiementID");


CREATE INDEX "IX_VenteServices_ServiceID" ON "VenteServices" ("ServiceID");


SELECT setval(
    pg_get_serial_sequence('"Categories"', 'ID'),
    GREATEST(
        (SELECT MAX("ID") FROM "Categories") + 1,
        nextval(pg_get_serial_sequence('"Categories"', 'ID'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"MoyensPaiement"', 'ID'),
    GREATEST(
        (SELECT MAX("ID") FROM "MoyensPaiement") + 1,
        nextval(pg_get_serial_sequence('"MoyensPaiement"', 'ID'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'UserId'),
    GREATEST(
        (SELECT MAX("UserId") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'UserId'))),
    false);


